### ISSUE TITLE
Capability with UnoCSS?

### ISSUE THREAD

**Issue by AllanChain** [Thinker-ljn/vite-plugin-tampermonkey#1]
I'm trying to use UnoCSS with this plugin. While everything works well in development, UnoCSS fails to generate bundle when building:

```
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
error during build:
Error: [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
```

That's because UnoCSS tries to find placeholders in CSS files, but there is none since this plugin puts all CSS code into JS files.

```js
// unocss code
    {
      name: 'unocss:global:build:generate',
      apply(options, { command }) {
        return command === 'build' && !options.build?.ssr
      },
      enforce: 'post',
      // rewrite the css placeholders
      async generateBundle(_, bundle) {
        const files = Object.keys(bundle)
        const cssFiles = files
          .filter(i => i.endsWith('.css'))
        // ...
```

Is it possible to use UnoCSS with this plugin? Or can we put CSS into JS after UnoCSS finishes processing?

**Comment by Thinker-ljn** [comment]
I also ran into this problem myself and haven't had time to fix it yet.
我自己遇到了这个问题，但还没有时间解决它。

I think this problem can be solved, I will try to solve it with your solution when I have time.
我觉得这个问题是可以解决，我有空时会尝试用你的方案解决一下。
